# Generated by Django 5.0.4 on 2024-08-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_owner_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Sample Name', max_length=255),
        ),
    ]
